### PR TITLE
wip Conversion add Rmd, feedback requested

### PR DESCRIPTION
**Pull request by villafup**
@Bioconductor/sweave2rmd

### CODE REVIEW

**Comment by hpages** [comment]
Hi @villafup What's the status of this PR? It's been dormant for 3 months (since Jul 13). I see it's marked as a draft. Will someone take a look at it, or has it been superseded by another PR? Thanks

**Comment by villafup** [comment]
Hi @hpages.  I will self-review this weekend.

**Comment by hpages** [comment]
Thanks @villafup

**Comment by hpages** [comment]
No follow up? I'm going to interpret the lack of answer or activity as a sign that this PR has been abandonned.

**Pull request closed without merging**
