### PR TITLE
Enable "offline mode" for felCat9

### PR DESCRIPTION
**Pull request by kakopo**

### CODE REVIEW

**Comment by hpages** [comment]
Thanks @kakopo for the PR. I wonder why the edit to `felCat9.R` is included in this PR. This was part of your previous PR (PR #65) and has been merged already. Maybe you need to resync your fork? Try that and we'll see if that fixes the problem.

**Comment by kakopo** [comment]
I've just synced the fork. Has this managed to solve the problem?

**Comment by hpages** [comment]
Yep, that was it. Thanks!

**Comment by kakopo** [comment]
Awesome!

**Pull request merged**
