### PR TITLE
Add 'organism' argument to registered_UCSC_genomes()

### PR DESCRIPTION
**Pull request by kakopo**
Added the organism argument to the `registered_UCSC_genomes()` function. This argument is set to `NA` by default. The changes made were documented in `GenomeInfoDb/man/getChromInfoFromUCSC.Rd`.

### CODE REVIEW

**Comment by hpages** [comment]
All right.

This looks good. Just a couple of very minor details about code formatting and other cosmetic:

- We use 4-space indentation increments for R code in Bioconductor. The code inside your `if` statement uses a 2-space increment w.r.t. the rest of the block. Please increase to a 4-space increment.

- Here's a little twist about the terminology. "UCSC genomes" are technically speaking _genome assemblies_, like the NCBI genome assemblies that we've been dealing with. However, in the case of UCSC, we refer to these genome assemblies  as "UCSC genomes", because (1) that's a little bit shorter and (2) that's how the UCSC Genome Browser people call them. OTOH, the NCBI website refers to those genome assemblies as just "assemblies". So we're doing the same in the **GenomeInfoDb**'s code and documentation. We use "UCSC genomes" to refer to the genome assemblies available in the UCSC Genome Browser, and "NCBI assemblies" to refer to the genome assemblies available in the NCBI assembly database [here](https://www.ncbi.nlm.nih.gov/assembly). This is also the reason why the first arguments in the `getChromInfoFromNCBI()` and `getChromInfoFromUCSC()` functions are called `assembly` and `genome`, respectively. The truth is that in both cases, the value that we pass to this argument is the name of a genome assembly.
  All this to say that you should replace "assemblies" with "genomes" in the description of the `organism` argument, for consistency with the rest of man page.

Finally, it would be nice to add an example of how to use this new feature e.g. you could add a call to `registered_UCSC_genomes("homo")` or `registered_UCSC_genomes("felis")` or both, just below the call to `registered_UCSC_genomes()` in the `\examples` section. Preceded by a 1-line comment explaining what the call does. 

Something like this:
```
## All registered UCSC genomes for Homo sapiens:
registered_UCSC_genomes("homo")

## All registered UCSC genomes for Felis catus (domestic cat):
registered_UCSC_genomes("felis")
```

Thanks!

**Comment by kakopo** [comment]
Done! I am glad that the mistake I made led to a helpful comment on the discrepancy between NCBI assemblies and UCSC genomes. I thought the difference was something heavy, when its just naming length, lol. 
I have done the necessary changes but I wanted to know if adding 
```
## All registered UCSC genomes for Felis catus (domestic cat):
registered_UCSC_genomes(organism = Felis catus")
```
to the examples would be okay instead? Just as a contrast with the `Homo sapiens` example to show different ways using the argument can be modified.

**Comment by hpages** [comment]
yes that's fine, but... does this example actually works? (try to run it, we should always try our code, even after we make very small changes)

**Comment by kakopo** [comment]
Apologies. I should have caught that. All fixed now! 
Thank you.

**Comment by hpages** [comment]
Perfect!

**Pull request merged**
