### PR TITLE
Link gorGor6 (UCSC genome) to Kamilah_GGO_v0 (NCBI assembly)

### PR DESCRIPTION
**Pull request by kakopo**
closes issue #62

### CODE REVIEW

**Comment by hpages** [comment]
So this PR has conflicts with the current **GenomeInfoDb** because it adds again stuff that was already merged by PR #88. Make sure this new PR only adds the new part which is the `NCBI_LINKER` part. Thanks!

**Comment by hpages** [comment]
Looks like your `NCBI-assembly-Kamilah_GGO_v0` branch doesn't have your previous work (the `gorGor6.R` and `Gorilla_gorilla_gorilla.R` files). Did you resync your fork and merge the master branch into your `NCBI-assembly-Kamilah_GGO_v0` branch? Thanks

**Comment by hpages** [comment]
@kakopo Hi Kirabo, are you going to follow up on this? I'll take another look at this as soon as I hear back from you. Thanks

**Comment by kakopo** [comment]
Hi Hervé, sorry about the delay in finishing this issue. I had put it on the back-burner as I finished wrapping up the internship, especially since the branch issue was giving me a bit of a hard time. I intend to finish it this week, however. I hope that this is alright!

**Comment by hpages** [comment]
Sure, no problem. Just let me know when it's ready for me to take another look at it. Thanks!

**Comment by kakopo** [comment]
@hpages Hi Hervé, sorry again for the delay on this issue. It seemed quite intimidating but I've been able to finally solve it. Please take a look at this [branch](https://github.com/kakopo/GenomeInfoDb/blob/NCBI-assembly-Kamilah_GGO_v0/inst/registered/UCSC_genomes/gorGor6.R) on your end and let me know if it looks as expected, thanks!

**Comment by hpages** [comment]
@kakopo Thanks. Note that you're providing a link to the `NCBI-assembly-Kamilah_GGO_v0` branch which is not what this PR is based on. However it looks like I mentioned the `NCBI-assembly-Kamilah_GGO_v0` branch in one of my previous comments,  when I actually meant `Link-gorGor6-to-Kamilah_GGO_v0`. My mistake, and sorry if that added to the confusion.

To summarize, when you submit a PR, you always want to make sure that (in this order):

1. You have succesfully resynced your GenomeInfoDb fork. That seems to be the case based on:

Screenshot from 2023-03-13 10-16-22

2. You have merged your default branch into the branch that this PR is based on. Note that this PR is based on your `Link-gorGor6-to-Kamilah_GGO_v0` branch so that's the only branch that matters in the context of this PR. That also seems to be the case based on:

image

Maybe you forgot to do 1. or 2. or both last time I checked this PR about 2 weeks ago, which is why the PR had conflicts or your `Link-gorGor6-to-Kamilah_GGO_v0` branch was missing some files.

But everything looks fine now so time to merge :wink:

**Comment by kakopo** [comment]
Yes, I think this was the case! At least now, I think I understand branches so this was a good experience, even if it took a bit long! Thanks.

**Pull request merged**
