### PR TITLE
Register felCat9

### PR DESCRIPTION
**Pull request by kakopo**

### CODE REVIEW

**Comment by hpages** [comment]
Thanks @kakopo for the PR.

The PR looks good.

Let's talk about code formatting. We prefer to use 4-space increments for indentation of R code. Please increase the indent of the code in the body of the `.order_seqlevels()` and `FETCH_ORDERED_CHROM_SIZES()` functions to 4 spaces. We also try to avoid lines of more than 80 characters. So for example this code:
```
ASSEMBLED_MOLECULES <- paste0("chr",
                              c("A1", "A2", "A3", "B1", "B2", "B3", "B4", "C1", "C2", "D1", "D2", "D3", "D4", "E1", "E2", "E3", "F1", "F2", "X", "M"))
```
could be formatted like this:
```
ASSEMBLED_MOLECULES <- paste0("chr", c("A1", "A2", "A3",
                                       "B1", "B2", "B3", "B4",
                                       "C1", "C2", "D1",
                                       "D2", "D3", "D4",
                                       "E1", "E2", "E3",
                                       "F1", "F2",
                                       "X", "M"))
```
You could also slightly modify it to do this:
```
ASSEMBLED_MOLECULES <- paste0("chr", c(paste0("A", 1:3),
                                       paste0("B", 1:4),
                                       paste0("C", 1:2),
                                       paste0("D", 1:4),
                                       paste0("E", 1:3),
                                       paste0("F", 1:2),
                                       "X", "M"))
```
A good test is to do `diff galGal6.R felCat9.R` at the Unix command line. The output of this command should be as small as possible i.e. it should show only the _real_ differences between the 2 files.

Thanks!

**Comment by kakopo** [comment]
Thank you. I carried out the much needed changes and ran `diff galGal6.R felCat9.R`. The results seemed satisfactory.

**Comment by hpages** [comment]
Hi @kakopo ,

Thanks for improving the formatting of the file. It looks cleaner now.

One last small detail. `diff galGal6.R felCat9.R` produces the following output for me:
```
hpages@spectre:~/github/kakopo/GenomeInfoDb/inst/registered/UCSC_genomes$ diff galGal6.R felCat9.R
1,3c1,9
< GENOME <- "galGal6"
< ORGANISM <- "Gallus gallus"
< ASSEMBLED_MOLECULES <- paste0("chr", c(1:28, 30:33, "W", "Z", "M"))
---
> GENOME <- "felCat9"
> ORGANISM <- "Felis catus"
> ASSEMBLED_MOLECULES <- paste0("chr", c(paste0("A", 1:3),
>                                        paste0("B", 1:4),
>                                        paste0("C", 1:2),
>                                        paste0("D", 1:4),
>                                        paste0("E", 1:3),
>                                        paste0("F", 1:2),
>                                        "X", "M"))
10c16
< {
---
> { 
14c20
< 
---
>     
20c26
< 
---
>     
29c35
< 
---
>     
36c42
< 
---
>     
49,51d54
< NCBI_LINKER <- list(
<     assembly_accession="GCA_000002315.5"
< )
53d55
< ENSEMBL_LINKER <- "chromAlias"
```
As you can see, the `diff` command reports small differences that are not immediately obvious. For example, this
```
20c26
< 
---
>     
```
means that line 20 in the left file and line 26 in the right file are different, even though we don't actually see a difference. These "invisible" differences are usually caused by white spaces, most of the time by _trailing_ white spaces.

Trailing white spaces don't serve any purpose other than polluting the file, so they should be avoided. Please get rid of them. You want to make sure that `diff galGal6.R felCat9.R` produces a clean output, that is, an output that only shows the meaningful differences between the 2 files.

Let me know if you have questions.

**Comment by kakopo** [comment]
@hpages done! Wow, I had not even noticed the trailing white space as an issue. Hope the script is satisfactory now.

**Comment by hpages** [comment]
Yeah, now we have a very clean output:
```
hpages@spectre:~/github/kakopo/GenomeInfoDb/inst/registered/UCSC_genomes$ diff galGal6.R felCat9.R
1,3c1,9
< GENOME <- "galGal6"
< ORGANISM <- "Gallus gallus"
< ASSEMBLED_MOLECULES <- paste0("chr", c(1:28, 30:33, "W", "Z", "M"))
---
> GENOME <- "felCat9"
> ORGANISM <- "Felis catus"
> ASSEMBLED_MOLECULES <- paste0("chr", c(paste0("A", 1:3),
>                                        paste0("B", 1:4),
>                                        paste0("C", 1:2),
>                                        paste0("D", 1:4),
>                                        paste0("E", 1:3),
>                                        paste0("F", 1:2),
>                                        "X", "M"))
49,51d54
< NCBI_LINKER <- list(
<     assembly_accession="GCA_000002315.5"
< )
53d55
< ENSEMBL_LINKER <- "chromAlias"
```
No distraction! Other people that work on other registration files might want to compare their file to `felCat9.R` and they will appreciate that `diff` produces such a clean output. :sparkles: 

Also note that after you add a new file to git, `git diff --cached` will display the content of the new file, and trailing white spaces will show up in red! It's git way to tell you that you probably want to get rid of those trailing white spaces.

I'm merging this now and I'll close issue #49 soon. Remember to record your contribution on Outreachy at https://www.outreachy.org/outreachy-december-2022-internship-round/communities/bioconductor/refactor-the-bsgenomeforge-tools/contributions/

**Comment by kakopo** [comment]
Awesome! I spent quite a bit of time trying to figure out where those white spaces could have been - `git diff --cached` is a pretty neat command! Thank you.

**Comment by hpages** [comment]
You're welcome!

**Pull request merged**
